### ISSUE TITLE
Forces tsconfig.json to remove all comments

### ISSUE THREAD

**Issue by bytniak** [swimauger/tsc-hooks#1]
After installing tsc-hooks it forces tsconfig.json to strictly follow json standard, while typescript permits comments.  

```
yarn run v1.22.10
$ tsc
internal/modules/cjs/loader.js:1052
    throw err;
    ^

SyntaxError: /home/project/tsconfig.json: Unexpected token / in JSON at position 661
    at parse (<anonymous>)
```

**Comment by swimauger** [comment]
Thanks for the first issue @bytniak, 

Working it into version 1.0.5 rn!

**Comment by swimauger** [comment]
Fixed by commit https://github.com/swimauger/tsc-hooks/commit/1827dcdcf42f8599b8db930972a90e7937ff2c5c

Update tsc-hooks to version ^1.0.5
