### ISSUE TITLE
TypeError: Cannot read property 'include' of undefined

### ISSUE THREAD

**Issue by ivankhm** [swimauger/tsc-hooks#10]
Hello! I'm trying to compile my project with `tsc-hooks`, but it crashes, with an error message in the console. 
I have `tsc-hooks` and `typescript` installed locally in the project.

`ts-hooks` version: `^1.0.9-dev.20210715.1`
`typescript` version: `^4.3.2`
tsconfig.json:
```json
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es2019",
		"outDir": "out",
		"lib": [
			"es2019"
		],
		"sourceMap": true,
		"rootDir": "src",
		"strict": true
	},
	"include": [ "src/**/*" ],
	"exclude": [
		"node_modules",
		".vscode-test",
	],
	"hooks": [ "copy-files" ]
}
```

Command i run: `tsc -p ./`

The error message I receive:
<details>
  <summary>Error message</summary>

  ```
  C:\Users\ivank\Documents\VSCodeProjects\VSCodeExtentions\deox-boilerplate\node_modules\tsc-hooks\hooks\copy-files.js:12
      const include = this.tsconfig.include?.map(file => path.resolve(this.tsconfigDir, file));
                                    ^
  
  TypeError: Cannot read property 'include' of undefined
      at Object.onPostCompilation (C:\Users\ivank\Documents\VSCodeProjects\VSCodeExtentions\deox-boilerplate\node_modules\tsc-hooks\hooks\copy-files.js:12:35)
      at process.emit (events.js:412:35)
      at process.exit (internal/process/per_thread.js:169:15)
      at C:\Users\ivank\Documents\VSCodeProjects\VSCodeExtentions\deox-boilerplate\node_modules\typescript\lib\tsc.js:4574:69
      at disableCPUProfiler (C:\Users\ivank\Documents\VSCodeProjects\VSCodeExtentions\deox-boilerplate\node_modules\typescript\lib\tsc.js:4685:21)
      at Object.exit (C:\Users\ivank\Documents\VSCodeProjects\VSCodeExtentions\deox-boilerplate\node_modules\typescript\lib\tsc.js:4574:21)
      at performCompilation (C:\Users\ivank\Documents\VSCodeProjects\VSCodeExtentions\deox-boilerplate\node_modules\typescript\lib\tsc.js:97604:20)
      at executeCommandLineWorker (C:\Users\ivank\Documents\VSCodeProjects\VSCodeExtentions\deox-boilerplate\node_modules\typescript\lib\tsc.js:97485:17)     
      at Object.executeCommandLine (C:\Users\ivank\Documents\VSCodeProjects\VSCodeExtentions\deox-boilerplate\node_modules\typescript\lib\tsc.js:97530:20)    
      at Object.<anonymous> (C:\Users\ivank\Documents\VSCodeProjects\VSCodeExtentions\deox-boilerplate\node_modules\typescript\lib\tsc.js:97818:4)
  
  ```

</details>

I tried to debug it and added `console.log(this)` before the place of the error, here is the output:
```js
{
  glob: <ref *1> [Function: glob] {
    sync: [Function: globSync] { GlobSync: [Function: GlobSync] },
    GlobSync: [Function: GlobSync],
    glob: [Circular *1],
    hasMagic: [Function (anonymous)],
    Glob: [Function: Glob]
  },
  config: {
    compilerOptions: {
      module: 'commonjs',
      target: 'es2019',
      outDir: 'out',
      lib: [Array],
      sourceMap: true,
      rootDir: 'src',
      strict: true
    },
    include: [
      'src/**/*',
    ],
    exclude: [ 'node_modules', '.vscode-test' ],
    hooks: [ 'copy-files' ]
  },
  tsconfigDir: 'C:\\Users\\ivank\\Documents\\VSCodeProjects\\VSCodeExtentions\\deox-boilerplate',
  tsconfigPath: 'C:\\Users\\ivank\\Documents\\VSCodeProjects\\VSCodeExtentions\\deox-boilerplate\\tsconfig.json',
  args: {}
}
```
So it seems I have some version error, because `this` has a bit different API, then your project expecting.

What you can recommend to do, to fix this?

**Comment by swimauger** [comment]
For now, probably best to use the most stable release version `1.0.9`.

So run:
`yarn remove tsc-hooks && yarn add tsc-hooks@1.0.9`

Right now, I've been working on ways to create local hooks, online hooks, pass arguments, and just a lot of destructive things lol, but best to use a stable release. I'll update the docs to reflect that.

**Comment by ivankhm** [comment]
Gonna try it, thank you!

**Comment by aleksclark** [comment]
Got the same error on 1.0.9-dev.20210715.1, with typescript 4.3.5

**Comment by swimauger** [comment]
@aleksclark 
I will hopefully rollout a new version here soon for v1.1.0, but until then probably best to use version `1.0.8`.

So again run:
`yarn remove tsc-hooks && yarn add tsc-hooks@1.0.8 --dev`

Just as an FYI @ivankhm, not sure if you already figured this out, but there is no version `1.0.9` sorry about that.

In the future I'm going to tag the dev versions as `dev`, so that when you install without a tag, i.e. 
`npm i tsc-hooks --save-dev` or `yarn add tsc-hooks --dev`, it will install the latest stable release.

I will keep this issue open until the new version releases
