### ISSUE TITLE
@swimauger

### ISSUE THREAD

**Issue by sanqi377** [swimauger/tsc-hooks#13]
@swimauger 
t's a shame.
This error message appears：
No inputs were found in config file 'C:/Users/sanqi/Desktop/w-qui/tsconfig.json'. Specified 'include' paths were '["src/**/*.wxml","src/**/*.wxss","src/**/*.json"]' and 'exclude' paths were '["dist"]'.

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "outDir": "dist",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
  },
  "include": [
    "src/**/*.wxml",
    "src/**/*.wxss",
    "src/**/*.json",
    "src/**/*.ts",
  ],
  "hooks": [
    "copy-files"
  ]
}
```

This allows you to run. But still no effect

_Originally posted by @sanqi377 in https://github.com/swimauger/tsc-hooks/issues/11#issuecomment-903407927_

**Comment by swimauger** [comment]
@sanqi377 I believe this is an error thrown by TypeScript when you don't have any TypeScript files. Can you send a picture of your folder/file structure?

**Comment by swimauger** [comment]
Hey @sanqi377,

Sorry things are still not working for you, I'm still working on some unexpected bugs, but maybe try using "src/**/*" in include and just use exclude to ignore files you don't want.

This might work, but I haven't tested it, so wouldn't know for sure. Let me know how it goes.

**Comment by swimauger** [comment]
@sanqi377 try out the newest version of tsc-hooks, version `tsc-hooks@1.1.1-patch.1`. I believe the patch will fix this exact issue 😄
