### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by MarcGirouxLeeroy** [swimauger/tsc-hooks#3]
Whatever i put into include will make tsc crash saying there are not .ts files in the folder i want to copy to the build folder. Even if add one.. hooks does nothing to copy files over. From your example, it does not work.

![Screen Shot 2021-06-09 at 10 19 00 AM](https://user-images.githubusercontent.com/33124675/121372249-21df3980-c90c-11eb-9570-cda299aeeae2.png)
![Screen Shot 2021-06-09 at 10 18 35 AM](https://user-images.githubusercontent.com/33124675/121372253-21df3980-c90c-11eb-842b-77c1dc40d2d7.png)

**Comment by swimauger** [comment]
Hi @foundationframework,

I just pushed changes for 1.0.6 that fixes a major issue with directories. Can you please run `yarn upgrade tsc-hooks` and try again?

**Comment by swimauger** [comment]
Additionally, I noticed in your screenshot you have a file called `test.js` you might be trying to copy over? If so, you don't need tsc-hooks to copy over JavaScript files, you simply need to set `allowJS` to true in `compilerOptions` like so:

```json5
{
  "compilerOptions": {
    "outDir": "dist",
    "allowJS": true
  },
  "include": [ "src/templates/assq/**/*" ]
}
```
