### ISSUE TITLE
Doesn't match src directory structure

### ISSUE THREAD

**Issue by tycrek** [swimauger/tsc-hooks#6]
Slowly migrating my project to TypeScript (for the 30th time, nothing but issues every time I try...) and I'm trying to use this to move my Pug views from `src/` to `out/`. My `tsconfig.json` is as follows:

```json
{
	"compilerOptions": {
		"outDir": "./out",
		"allowJs": true,
		"target": "es6",
		"module": "commonjs",
		"esModuleInterop": true
	},
	"include": [
		"./src/**/*"
	],
	"hooks": [
		"copy-files"
	]
}
```

After running `tsc`, the result is this (plus my other `.js` files as expected, but those are in the proper dirs): 
![image](https://user-images.githubusercontent.com/29926144/123686931-8efc3580-d80d-11eb-91ef-a4240e4a6933.png)

How could I go about fixing this?

**Comment by swimauger** [comment]
Perhaps try specifying a root directory in the `compilerOptions`... Something like this maybe
<pre>
{
	"compilerOptions": {
		"outDir": "./out",
		<b>"rootDir": "./src",</b> // <-- Change Here
		"allowJs": true,
		"target": "es6",
		"module": "commonjs",
		"esModuleInterop": true
	},
	"include": [
		"src/**/*"
	],
	"hooks": [
		"copy-files"
	]
}
</pre>

**Comment by michael-proulx** [comment]
I experience something similaire while trying your tool. I tried `rootDir` but it didn't work, do you have any other tips?

version: 1.0.8

```
{
  "compilerOptions": {
    "outDir": "./dist",
    "rootDir": "./src",
    "target": "es6",
    "module": "es6",
    "jsx": "react",
    "declaration": true,
    "strict": true
  },
  "include": ["src/**/*"],
  "hooks": ["copy-files"]
}
```

![image](https://user-images.githubusercontent.com/23478544/128359652-3ec683ed-1a68-4bee-b48e-15e0d267042c.png)
![image](https://user-images.githubusercontent.com/23478544/128359685-9947ece8-ce03-4e08-8297-c418a5c1ace9.png)
