### ISSUE TITLE
enable optional copying of js & ts files?

### ISSUE THREAD

**Issue by jonnyparris** [swimauger/tsc-hooks#7]
Firstly great job tackling this very specific and annoying shortcoming of typescript's build script 🙌🏾 .

Would it be possible to optionally remove this line as it fits a usecase* I have? https://github.com/swimauger/tsc-hooks/blob/cee978772d8fd5d30f51ca94a7b6b1c042b888aa/hooks/copy-files.js#L13
(There are some nested ts projects that I would like to copy without compiling as part of my parent level build).

I tried forking this project to just comment it out but installing from a github repo seems to break the post-install injection step because the module is cached in a different folder from where the `tsc` binary is installed.

Any tips/suggestion for the easiest/quickest way around this hurdle are much appreciated!

**Comment by swimauger** [comment]
Thanks @jonnyparris,

Interesting use case you have there.

If it were just JavaScript files to copy over, you can normally just use `allowJS` in compiler options; however, in your case it sounds like TypeScript, so I agree this can definitely be a feature.

I will add an `allowTS` option like so:

```json5
{
  "compilerOptions": {
    "outDir": "dist",
    "allowJS": true, /* <-- ALREADY EXISTS */
    "allowTS": true /* <-- NEW OPTION */
  },
  "include": [ "src/**/*" ],
  "exclude": [ "src/**/*.txt" ],
  "hooks": [ "copy-files" ] 
}
```

**Comment by jonnyparris** [comment]
Wow - thanks for the rapid turnaround!
However, I'm getting errors about `allowTS` as an invalid compiler option when trying to use it. 
Perhaps we could nest the flag under a different key instead - e.g. `"hookOptions": { "allowTS": true }`?
